name: llama_cpp_bindings
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  ffigen: ^16.1.0
  test: ^1.21.2


ffigen:
  name: LlamaBindings
  description: Bindings for llama.h from llama.cpp
  output: 'lib/src/generated_llama_cpp_bindings.dart'
  headers:
    entry-points:
      - '../../llama.cpp/include/llama.h'
  compiler-opts:
    - '-I../../llama.cpp/ggml/include'